### ISSUE TITLE
Cache deserialization issues cause no versions error

### ISSUE THREAD

**Issue by thatch** [hdeps/hdeps#27]
I think this is hitting https://github.com/psf/cachecontrol/issues/324 while fetching the same url concurrently in threads, which drops the body and we think there are no releases.

```
(.venv) [tim@rygel hdeps]$ time hdeps -p 4 --trace=foo tf-nightly
2024-02-19 14:33:15,860 WARNING  cachecontrol.controller:164 Cache entry deserialization failed, entry ignored
2024-02-19 14:33:15,968 WARNING  cachecontrol.controller:164 Cache entry deserialization failed, entry ignored
Traceback (most recent call last):
  File "/home/tim/code/hdeps/.venv/bin/hdeps", line 33, in <module>
    sys.exit(load_entry_point('hdeps', 'console_scripts', 'hdeps')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/hdeps/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/hdeps/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/tim/code/hdeps/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/hdeps/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/hdeps/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/hdeps/hdeps/cli.py", line 160, in main
    walker.drain()
  File "/home/tim/code/hdeps/hdeps/resolution.py", line 134, in drain
    version = find_best_compatible_version(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/hdeps/hdeps/compatibility.py", line 84, in find_best_compatible_version
    raise ValueError(f"{project.name} has no {python_version}-compatible release")
ValueError: grpcio has no 3.11.3-compatible release

real	0m5.894s
user	0m5.604s
sys	0m0.252s
```

**Comment by amjith** [comment]
Probably related to the same locking issue: 

```
$ hdeps nflx-kragle
Traceback (most recent call last):
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/urllib3/response.py", line 737, in _error_catcher
    yield
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/urllib3/response.py", line 883, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(0 bytes read, 1352679 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/urllib3/response.py", line 1043, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/urllib3/response.py", line 935, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/urllib3/response.py", line 861, in _raw_read
    with self._error_catcher():
  File "/opt/nflx/cpython-3.11.6/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/urllib3/response.py", line 761, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 1352679 more expected)', IncompleteRead(0 bytes read, 1352679 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amjith/.virtualenvs/hdeps/bin/hdeps", line 33, in <module>
    sys.exit(load_entry_point('hdeps', 'console_scripts', 'hdeps')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/netflix/github/hdeps/hdeps/cli.py", line 182, in main
    solve()
  File "/Users/amjith/netflix/github/hdeps/hdeps/cli.py", line 180, in solve
    walker.drain()
  File "/Users/amjith/netflix/github/hdeps/hdeps/resolution.py", line 155, in drain
    project = fut.result()
              ^^^^^^^^^^^^
  File "/opt/nflx/cpython-3.11.6/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/nflx/cpython-3.11.6/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/nflx/cpython-3.11.6/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/keke/__init__.py", line 267, in dec
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/netflix/github/hdeps/hdeps/resolution.py", line 98, in _fetch_project
    project_page = self.pypi_simple.get_project_page(project_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/pypi_simple/client.py", line 273, in get_project_page
    r = self.s.get(url, timeout=timeout, headers=request_headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amjith/.virtualenvs/hdeps/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read, 1352679 more expected)', IncompleteRead(0 bytes read, 1352679 more expected))
```

The issue went away after I deleted the cache manually.
